
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftSTARSLASHASSIGN ELSE IDENT IF LBRACE LET LPAREN MINUS NUMBER PLUS PRINT RBRACE RPAREN SEMI SLASH STAR WHILEexpr : expr SEMI exprexpr : NUMBERexpr : IDENTexpr : expr PLUS expr\n| expr MINUS expr\n| expr STAR expr\n| expr SLASH exprexpr : LPAREN expr RPAREN'
    
_lr_action_items = {'NUMBER':([0,4,5,6,7,8,9,],[2,2,2,2,2,2,2,]),'IDENT':([0,4,5,6,7,8,9,],[3,3,3,3,3,3,3,]),'LPAREN':([0,4,5,6,7,8,9,],[4,4,4,4,4,4,4,]),'$end':([1,2,3,11,12,13,14,15,16,],[0,-2,-3,-1,-4,-5,-6,-7,-8,]),'SEMI':([1,2,3,10,11,12,13,14,15,16,],[5,-2,-3,5,5,-4,-5,-6,-7,-8,]),'PLUS':([1,2,3,10,11,12,13,14,15,16,],[6,-2,-3,6,6,-4,-5,-6,-7,-8,]),'MINUS':([1,2,3,10,11,12,13,14,15,16,],[7,-2,-3,7,7,-4,-5,-6,-7,-8,]),'STAR':([1,2,3,10,11,12,13,14,15,16,],[8,-2,-3,8,8,8,8,-6,-7,-8,]),'SLASH':([1,2,3,10,11,12,13,14,15,16,],[9,-2,-3,9,9,9,9,-6,-7,-8,]),'RPAREN':([2,3,10,11,12,13,14,15,16,],[-2,-3,16,-1,-4,-5,-6,-7,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,4,5,6,7,8,9,],[1,10,11,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr SEMI expr','expr',3,'p_expr_multipleops','parser.py',17),
  ('expr -> NUMBER','expr',1,'p_expr_number','parser.py',22),
  ('expr -> IDENT','expr',1,'p_expr_identifier','parser.py',27),
  ('expr -> expr PLUS expr','expr',3,'p_expr_binop','parser.py',32),
  ('expr -> expr MINUS expr','expr',3,'p_expr_binop','parser.py',33),
  ('expr -> expr STAR expr','expr',3,'p_expr_binop','parser.py',34),
  ('expr -> expr SLASH expr','expr',3,'p_expr_binop','parser.py',35),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_group','parser.py',40),
]
